# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)


platform :ios do

  desc "Get application bundle id"
  lane :my_app_identifier do
      app_identifier =
	CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
      puts app_identifier
  end

  desc "Authenticate in AppStore Connect"
  lane :authenticate do
      app_store_connect_api_key(
       key_id: ENV["KEY_ID"],
       issuer_id: ENV["ISSUER_ID"],
       key_content: ENV["KEY_CONTENT"],
       is_key_content_base64: true
  )
  end

  desc "Sync certificates"
  lane :sync_certificates do
     #read-only disables match from overriding the existing certificates.
     match({readonly: true, type: "appstore"})
  end

  desc "Create ipa"
  lane :build do
     #update profiles
     sync_certificates
     # Increases the build number by 1
     increment_build_number
     # Creates a signed file
     gym
  end

  desc "Upload to TestFlight"
   lane :beta do
        authenticate()

        build()
        pilot(
            notify_external_testers: false,
            changelog: "This is my changelog of things that have changed in a log",
            ipa: "./fastlane/builds/BrightSky.ipa"
        )
   end
end
